/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package org.liferay.demo.conference.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.liferay.demo.conference.model.Speaker;
import org.liferay.demo.conference.service.SpeakerLocalServiceUtil;

/**
 * The extended model base implementation for the Speaker service. Represents a row in the &quot;CONFERENCE_Speaker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SpeakerImpl}.
 * </p>
 *
 * @author Milen Dyankov
 * @see SpeakerImpl
 * @see org.liferay.demo.conference.model.Speaker
 * @generated
 */
public abstract class SpeakerBaseImpl extends SpeakerModelImpl
	implements Speaker {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a speaker model instance should use the {@link Speaker} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			SpeakerLocalServiceUtil.addSpeaker(this);
		}
		else {
			SpeakerLocalServiceUtil.updateSpeaker(this);
		}
	}
}