/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package org.liferay.demo.conference.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.trash.TrashHandler;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.model.TrashedModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.trash.model.TrashEntry;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Speaker service. Represents a row in the &quot;CONFERENCE_Speaker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.liferay.demo.conference.model.impl.SpeakerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.liferay.demo.conference.model.impl.SpeakerImpl}.
 * </p>
 *
 * @author Milen Dyankov
 * @see Speaker
 * @see org.liferay.demo.conference.model.impl.SpeakerImpl
 * @see org.liferay.demo.conference.model.impl.SpeakerModelImpl
 * @generated
 */
public interface SpeakerModel extends BaseModel<Speaker>, StagedGroupedModel,
	TrashedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a speaker model instance should use the {@link Speaker} interface instead.
	 */

	/**
	 * Returns the primary key of this speaker.
	 *
	 * @return the primary key of this speaker
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this speaker.
	 *
	 * @param primaryKey the primary key of this speaker
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this speaker.
	 *
	 * @return the uuid of this speaker
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this speaker.
	 *
	 * @param uuid the uuid of this speaker
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the speaker ID of this speaker.
	 *
	 * @return the speaker ID of this speaker
	 */
	public long getSpeakerId();

	/**
	 * Sets the speaker ID of this speaker.
	 *
	 * @param speakerId the speaker ID of this speaker
	 */
	public void setSpeakerId(long speakerId);

	/**
	 * Returns the company ID of this speaker.
	 *
	 * @return the company ID of this speaker
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this speaker.
	 *
	 * @param companyId the company ID of this speaker
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this speaker.
	 *
	 * @return the group ID of this speaker
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this speaker.
	 *
	 * @param groupId the group ID of this speaker
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this speaker.
	 *
	 * @return the user ID of this speaker
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this speaker.
	 *
	 * @param userId the user ID of this speaker
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this speaker.
	 *
	 * @return the user uuid of this speaker
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this speaker.
	 *
	 * @param userUuid the user uuid of this speaker
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this speaker.
	 *
	 * @return the user name of this speaker
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this speaker.
	 *
	 * @param userName the user name of this speaker
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this speaker.
	 *
	 * @return the create date of this speaker
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this speaker.
	 *
	 * @param createDate the create date of this speaker
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this speaker.
	 *
	 * @return the modified date of this speaker
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this speaker.
	 *
	 * @param modifiedDate the modified date of this speaker
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this speaker.
	 *
	 * @return the status of this speaker
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this speaker.
	 *
	 * @param status the status of this speaker
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this speaker.
	 *
	 * @return the status by user ID of this speaker
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this speaker.
	 *
	 * @param statusByUserId the status by user ID of this speaker
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this speaker.
	 *
	 * @return the status by user uuid of this speaker
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this speaker.
	 *
	 * @param statusByUserUuid the status by user uuid of this speaker
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this speaker.
	 *
	 * @return the status by user name of this speaker
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this speaker.
	 *
	 * @param statusByUserName the status by user name of this speaker
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this speaker.
	 *
	 * @return the status date of this speaker
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this speaker.
	 *
	 * @param statusDate the status date of this speaker
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the name of this speaker.
	 *
	 * @return the name of this speaker
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this speaker.
	 *
	 * @param name the name of this speaker
	 */
	public void setName(String name);

	/**
	 * Returns the bio of this speaker.
	 *
	 * @return the bio of this speaker
	 */
	@AutoEscape
	public String getBio();

	/**
	 * Sets the bio of this speaker.
	 *
	 * @param bio the bio of this speaker
	 */
	public void setBio(String bio);

	/**
	 * Returns the trash entry created when this speaker was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this speaker.
	 *
	 * @return the trash entry created when this speaker was moved to the Recycle Bin
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public TrashEntry getTrashEntry() throws PortalException, SystemException;

	/**
	 * Returns the class primary key of the trash entry for this speaker.
	 *
	 * @return the class primary key of the trash entry for this speaker
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this speaker.
	 *
	 * @return the trash handler for this speaker
	 */
	@Override
	public TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this speaker is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this speaker is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this speaker is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this speaker is in the Recycle Bin; <code>false</code> otherwise
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public boolean isInTrashContainer();

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved()}
	 */
	@Override
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this speaker is approved.
	 *
	 * @return <code>true</code> if this speaker is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this speaker is denied.
	 *
	 * @return <code>true</code> if this speaker is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this speaker is a draft.
	 *
	 * @return <code>true</code> if this speaker is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this speaker is expired.
	 *
	 * @return <code>true</code> if this speaker is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this speaker is inactive.
	 *
	 * @return <code>true</code> if this speaker is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this speaker is incomplete.
	 *
	 * @return <code>true</code> if this speaker is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this speaker is pending.
	 *
	 * @return <code>true</code> if this speaker is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this speaker is scheduled.
	 *
	 * @return <code>true</code> if this speaker is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Speaker speaker);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Speaker> toCacheModel();

	@Override
	public Speaker toEscapedModel();

	@Override
	public Speaker toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}